### ISSUE TITLE
Save controls in extension dictionary

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ClosedLoopReachability.jl#40]

**Comment by mforets** [comment]
This should be fairly easy to do. We have to save the intermediate control values generated in 

https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/37a87c0ffea1db7c91a3f7dac79c4dd2ff10f9a6/src/solve.jl#L129

in a dictionary, and pass such dictionary to the constructor of the output flowpipe, in this case a `MixedFlowpipe`. So we can use [this constructor](https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/src/Flowpipes/flowpipes.jl#L711).

**Comment by mforets** [comment]
fixed in #64

**Comment by mforets** [comment]
**TODO document**

**Comment by schillic** [comment]
Now that we have splitting, this dictionary is not useful anymore. I think the controls should be added to each individual flowpipe instead.
